# Generated by Django 2.0.3 on 2018-03-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_auto_20180321_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_bookmarked',
            field=models.BooleanField(default=0),
        ),
    ]
